export const currencyByRupee: Currency[] = [
  {
    name: 'US DOLLAR',
    value: 0.012271428,
    flag: '🇺🇸',
    symbol: '$',
  },
  {
    name: 'EURO',
    value: 0.01125809,
    flag: '🇪🇺',
    symbol: '€',
  },
  {
    name: 'BRITISH POUND',
    value: 0.0099194378,
    flag: '🇬🇧',
    symbol: '£',
  },
  {
    name: 'RUSSIAN RUBLE',
    value: 0.85040469,
    flag: '🇷🇺',
    symbol: '₽',
  },
  {
    name: 'AUSTRALIAN DOLLAR',
    value: 0.01732574,
    flag: '🇦🇺',
    symbol: 'A$',
  },
  {
    name: 'CANADIAN DOLLAR',
    value: 0.016457908,
    flag: '🇨🇦',
    symbol: 'C$',
  },
  {
    name: 'JAPANESE YEN',
    value: 1.5909089,
    flag: '🇯🇵',
    symbol: '¥',
  },
  {
    name: 'KUWAITI DINAR',
    value: 0.0037446993,
    flag: '🇰🇼',
    symbol: 'KD',
  },
  {
    name: 'BITCOIN',
    value: 0.000000543544886,
    flag: '🎰',
    symbol: '₿',
  },
  {
    name: 'SWISS FRANC',
    value: 0.011548269,
    flag: '🇨🇭',
    symbol: 'CHF',
  },
  {
    name: 'SWEDISH KRONA',
    value: 0.11423914,
    flag: '🇸🇪',
    symbol: 'SEK',
  },
  {
    name: 'SINGAPORE DOLLAR',
    value: 0.016847586,
    flag: '🇸🇬',
    symbol: 'S$',
  },
  {
    name: 'HONG KONG DOLLAR',
    value: 0.095167398,
    flag: '🇭🇰',
    symbol: 'HK$',
  },
  {
    name: 'INDIAN RUPEE',
    value: 1,
    flag: '🇮🇳',
    symbol: '₹',
  },
  {
    name: 'NEW ZEALAND DOLLAR',
    value: 0.018596824,
    flag: '🇳🇿',
    symbol: 'NZ$',
  },
  {
    name: 'SOUTH AFRICAN RAND',
    value: 0.17318564,
    flag: '🇿🇦',
    symbol: 'R',
  },
  {
    name: 'MEXICAN PESO',
    value: 0.24558732,
    flag: '🇲🇽',
    symbol: 'MXN$',
  },
  {
    name: 'BRAZILIAN REAL',
    value: 0.065432874,
    flag: '🇧🇷',
    symbol: 'R$',
  },
  {
    name: 'NORWEGIAN KRONE',
    value: 0.11876352,
    flag: '🇳🇴',
    symbol: 'NOK',
  },
  {
    name: 'CHINESE YUAN',
    value: 0.078652319,
    flag: '🇨🇳',
    symbol: '¥',
  },
  {
    name: 'MALAYSIAN RINGGIT',
    value: 0.050123487,
    flag: '🇲🇾',
    symbol: 'RM',
  },
  {
    name: 'ARGENTINE PESO',
    value: 1.3147892,
    flag: '🇦🇷',
    symbol: '$',
  },
  {
    name: 'THAI BAHT',
    value: 0.39685421,
    flag: '🇹🇭',
    symbol: '฿',
  },
  {
    name: 'TURKISH LIRA',
    value: 0.10473259,
    flag: '🇹🇷',
    symbol: 'TRY',
  },
  {
    name: 'EGYPTIAN POUND',
    value: 0.2745938,
    flag: '🇪🇬',
    symbol: 'EGP',
  },
  {
    name: 'SOUTH KOREAN WON',
    value: 14.546982,
    flag: '🇰🇷',
    symbol: '₩',
  },
  {
    name: 'SAUDI RIYAL',
    value: 0.045678213,
    flag: '🇸🇦',
    symbol: 'SAR',
  },
  {
    name: 'INDONESIAN RUPIAH',
    value: 176.54231,
    flag: '🇮🇩',
    symbol: 'IDR',
  },
  {
    name: 'UNITED ARAB EMIRATES DIRHAM',
    value: 0.056784235,
    flag: '🇦🇪',
    symbol: 'AED',
  },
  {
    name: 'ISRAELI SHEKEL',
    value: 0.039284567,
    flag: '🇮🇱',
    symbol: '₪',
  },
  {
    name: 'QATARI RIYAL',
    value: 0.050987641,
    flag: '🇶🇦',
    symbol: 'QAR',
  },
  {
    name: 'VIETNAMESE DONG',
    value: 281.56784,
    flag: '🇻🇳',
    symbol: '₫',
  },
  {
    name: 'PHILIPPINE PESO',
    value: 0.63912874,
    flag: '🇵🇭',
    symbol: '₱',
  },
  {
    name: 'COLOMBIAN PESO',
    value: 47.982674,
    flag: '🇨🇴',
    symbol: 'COL$',
  },
  {
    name: 'POLISH ZLOTY',
    value: 0.048326594,
    flag: '🇵🇱',
    symbol: 'PLN',
  },
  {
    name: 'SRI LANKAN RUPEE',
    value: 2.1968473,
    flag: '🇱🇰',
    symbol: 'LKR',
  },
  {
    name: 'CZECH KORUNA',
    value: 0.27964513,
    flag: '🇨🇿',
    symbol: 'CZK',
  },
  {
    name: 'HUNGARIAN FORINT',
    value: 3.784562,
    flag: '🇭🇺',
    symbol: 'HUF',
  },
  {
    name: 'ROMANIAN LEU',
    value: 0.056932485,
    flag: '🇷🇴',
    symbol: 'RON',
  },
  {
    name: 'CROATIAN KUNA',
    value: 0.075489623,
    flag: '🇭🇷',
    symbol: 'HRK',
  },
  {
    name: 'BULGARIAN LEV',
    value: 0.022549784,
    flag: '🇧🇬',
    symbol: 'BGN',
  },
  {
    name: 'UKRAINIAN HRYVNIA',
    value: 0.37094826,
    flag: '🇺🇦',
    symbol: 'UAH',
  },
  {
    name: 'NIGERIAN NAIRA',
    value: 4.935782,
    flag: '🇳🇬',
    symbol: '₦',
  },
  {
    name: 'KENYAN SHILLING',
    value: 2.716543,
    flag: '🇰🇪',
    symbol: 'KES',
  },
];
  
  